config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  devise_for :users

  resource :image do
    member do
      get 'cached_image_url'
    end
  end
  resources :answers
  resources :comments
  resources :questions
  resources :users, only: [:index, :show]
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :owner, class_name: User, foreign_key: :owner_id
  belongs_to :owner_with_deleted, -> { with_deleted }, class_name: User, foreign_key: :owner_id
  has_many :comments, dependent: :destroy
  has_many :answers, dependent: :destroy

  validates :owner, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 200 }
  validates :post_text, presence: true, length: { minimum: 5, maximum: 9999 }

  def self.search(query)
    if query.blank? then
      all
    else
      where(post_text: query)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.search(params[:q]).order(created_at: :desc, id: :asc).includes(:owner_with_deleted).page(params[:page])

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to(@question, notice: 'Question was successfully created.')
    else
      render(:new)
    end
  end

  def update
    if @question.update(question_params)
      redirect_to(@question, notice: 'Question was successfully updated.')
    else
      render(:edit)
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:name, :post_text)
  end

end

app/views/questions/_form.html.haml
= simple_form_for @question do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, placeholder: 'Title', label: false
    = f.input :post_text, label: false

  %div{ class: 'preview' }

  .form-actions
    = f.button :submit

= render 'modules/photoswipe'

app/views/questions/_header.html.haml
%div{ class: 'header' }
  = link_to root_path, class: 'logo-with-text left' do
    %div{ class: 'underflow' } Underflow
  %ul{ class: 'right' }
    %li= link_to 'Questions', questions_path, class: 'label bg-light-gray'
    %li= link_to 'Users', users_path, class: 'label bg-light-gray'
    %li= link_to 'Ask Question', new_question_path, class: 'label bg-light-gray'

app/views/questions/_list.html.haml
%div{ id: 'questions-list' }
  =paginate @questions, remote: true
  %table
    - @questions.each do |question|
      %tr
        %td
          =link_to question do
            %div 0
            %div vote
        %td
          =link_to question do
            %div 1
            %div answer
        %td
          =link_to question do
            %div 38
            %div views
        %td
          %div=link_to question.name, question
          %div
            %div{ class: 'tags left' }
              %tag{ class: 'tag label'} java
              %tag{ class: 'tag label'} spring
            %div{ class: 'modified-time' } modified 12 min ago
            %div{ class: 'user-info' }=link_to (question.owner_with_deleted.display_name), user_path(question.owner_with_deleted.id)

app/views/questions/_top_bar.html.haml
- content_for :header_right, flash: true do
  - if user_signed_in?
    = link_to user_path(current_user), class: 'user-info' do
      =gravatar_image_tag current_user.email, gravatar: { d: :identicon, s: 26 }, class: 'user-icon'
      %span{ 'data-user-id' => "#{current_user.id}" } 9,999,999
  - else
    %ul{ class: 'sign-links'}
      %li= link_to 'Sign Up', new_user_registration_path, class: 'label bg-blue'
      %li= link_to 'Log In', new_user_session_path, class: 'label bg-blue'

  = simple_form_for :questions, url: questions_path, method: :get, remote: :true, html: { class: 'search-form', autocomplete: 'off' } do |f|
    = text_field_tag :q, nil, placeholder: 'search', as: :string, id: nil

app/views/questions/edit.html.haml
- content_for :page_title, 'New Question - Stack Underflow'

= render 'top_bar'
%div{ id: 'questions-edit', class: 'container' }
  = render 'header'
  = render 'form'

app/views/questions/index.html.haml
- content_for :page_title, 'Questions - Stack Underflow'

= render 'top_bar'
%div{ id: 'questions-index', class: 'container' }
  = render 'header'
  = simple_form_for :questions, url: questions_path, method: :get, remote: :true, html: { class: "search-form", autocomplete: 'off' } do |f|
    = text_field_tag :q, nil, as: :string, id: 'question-q'
  =render 'list'

app/views/questions/index.js.erb
(function () {
  var partial = $('#questions-list')
  partial.fadeOut(150, 'swing',
    function () {
      partial.html('<%= escape_javascript (render 'list') %>')
      $('.container > .search-form').show().find('#question-q').val('<%= escape_javascript (params[:q]) %>').focus()
      partial.fadeIn(200)
    })
})()

app/views/questions/new.html.haml
- content_for :page_title, 'New Question - Stack Underflow'

= render 'top_bar'
%div{ id: 'questions-new', class: 'container' }
  = render 'header'
  = render 'form'

app/views/questions/show.html.haml
-content_for :page_title, "#{@question.name} - Stack Underflow"

= render 'top_bar'
%div{ id: 'questions-show', class: 'container', 'data-params-id' => "#{params[:id]}" }
  = render 'header'

  %div{ id: 'question_name' }= @question.name
  %div{ class: 'vote' }
    %span{ class: 'upvote' } ▲
    %div{ class: 'vote-count' } 999
    %span{ class: 'downvote' } ▼

  %div{ class: 'preview' }
  %div{ id: 'question_post_text' }= @question.post_text

  - if @question.owner == current_user
    = link_to 'Edit', edit_question_path(@question), class: 'button'

= render 'modules/photoswipe'