config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  devise_for :users

  resource :image do
    member do
      get 'cached_image_url'
    end
  end
  resources :answers
  resources :comments
  resources :questions
  resources :users, only: [:index, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :owner, class_name: User, foreign_key: 'owner_id'
  belongs_to :owner_with_deleted, -> { with_deleted }, class_name: User, foreign_key: 'owner_id'
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_text)
    end
end

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :post_text

  .form-actions
    = f.button :submit

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Post text
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.post_text
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Post text:
  = @comment.post_text

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path