config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  devise_for :users

  resource :image do
    member do
      get 'cached_image_url'
    end
  end
  resources :answers
  resources :comments
  resources :questions
  resources :users, only: [:index, :show]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :owner, class_name: User, foreign_key: 'owner_id'
  belongs_to :owner_with_deleted, -> { with_deleted }, class_name: User, foreign_key: 'owner_id'
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:post_text)
    end
end

app/views/answers/_form.html.haml
= simple_form_for(@answer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :post_text

  .form-actions
    = f.button :submit

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %thead
    %tr
      %th Post text
      %th
      %th
      %th

  %tbody
    - @answers.each do |answer|
      %tr
        %td= answer.post_text
        %td= link_to 'Show', answer
        %td= link_to 'Edit', edit_answer_path(answer)
        %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Post text:
  = @answer.post_text

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path